/**
 * languageConfig.js
 * Central language registry for ASHA Saathi.
 *
 * Add a new language by adding a key here — everything else picks it up automatically.
 * Each language defines:
 *   - meta: display name, locale for speechSynthesis
 *   - ui: all UI strings in that language
 *   - signs: IMNCI danger sign labels (keyed by sign id)
 *   - keywords: NLP keyword arrays per sign id (what the worker might say aloud)
 */

export const LANGUAGES = {
  // ── English ─────────────────────────────────────────────────────────────────
  en: {
    meta: { name: "English", nativeName: "English", locale: "en-IN", whisperLang: "en" },
    ui: {
      appName: "ASHA Saathi",
      tagline: "WHO IMNCI · Offline Triage System",
      offlineReady: "Offline Ready",
      newAssessment: "New Assessment",
      newAssessmentSub: "Start triage for a new patient",
      viewQueue: "Today's Queue",
      viewQueueSub: "View and manage active patients",
      referralHistory: "Referral History",
      referralHistorySub: "Previous referrals stored locally",
      patientName: "Patient Name (Optional)",
      patientNamePlaceholder: "Enter name or leave blank",
      ageGroup: "Age Group",
      gender: "Gender",
      male: "Male",
      female: "Female",
      startVoice: "🎤 Start Voice Assessment",
      skipChecklist: "Skip Voice · Use Checklist",
      checklistTitle: "Danger Sign Checklist",
      checklistSubtitle: "WHO IMNCI Protocol",
      noSignsSelected: "No signs selected",
      signsSelected: (n) => `${n} sign${n > 1 ? "s" : ""} selected`,
      clearAll: "Clear all",
      assessPatient: "Assess Patient →",
      selectAtLeastOne: "Select at least one sign",
      voiceIdle: "Initialising...",
      voiceLoading: "Loading voice model (first time only)...",
      voiceReady: "🎤 Tap to speak",
      voiceRecording: "🔴 Recording... tap to stop",
      voiceTranscribing: "Processing speech...",
      voiceError: "Voice unavailable — use checklist",
      voiceHeard: "Heard",
      noiseNote: "Background noise suppression active",
      referImmediately: "REFER IMMEDIATELY",
      referIn24h: "REFER WITHIN 24 HOURS",
      localManagement: "LOCAL MANAGEMENT",
      speakResult: "🔊 Speak Result",
      addToQueue: "Add to Queue →",
      backToChecklist: "Back to Checklist",
      observedSigns: "Observed Danger Signs",
      familyHeadingRed: "Go to hospital NOW",
      familySubRed: "Child must be taken to PHC immediately",
      familyUrgencyRed: "Delay can be dangerous",
      familyHeadingYellow: "See a doctor within 24 hours",
      familySubYellow: "Take the child to PHC by tomorrow",
      familyUrgencyYellow: "Early treatment is important",
      familyHeadingGreen: "Care at home",
      familySubGreen: "No hospital visit needed right now",
      familyUrgencyGreen: "Continue routine care",
      familySignsLabel: "Observed danger signs",
      familyListen: "🔊 Listen",
      familyProtocol: "This information is based on the WHO IMNCI Protocol",
      familyPatient: "Patient",
      queueTitle: "Today's Queue",
      queueSubtitle: (n) => `${n} patients · ranked by urgency`,
      addNextPatient: "+ Add Next Patient",
      viewReport: "View Report",
      markReferred: "Mark Referred",
      referred: "✓ Referred",
      ageGroups: ["Infant (<1 yr)", "Child (1-5 yr)", "Older Child (5-12)", "Adult"],
    },
    signs: {
      not_able_to_drink: "Not able to drink or breastfeed",
      vomits_everything: "Vomits everything",
      convulsions: "Convulsions (fits) — now or recently",
      lethargic_unconscious: "Lethargic or unconscious / hard to wake",
      chest_indrawing: "Chest indrawing (chest pulls in when breathing)",
      stridor: "Stridor in calm child (noisy breathing at rest)",
      severe_dehydration: "Sunken eyes + skin pinch goes back very slowly",
      blood_in_stool: "Blood in stool",
      high_fever_with_stiff_neck: "High fever with stiff neck",
      bulging_fontanelle: "Bulging or sunken fontanelle (infant)",
      fast_breathing: "Fast breathing",
      some_dehydration: "Restless/irritable + sunken eyes (mild dehydration signs)",
      fever_no_stiff_neck: "Fever without stiff neck",
      ear_pain_discharge: "Ear pain or discharge",
      persistent_diarrhea: "Diarrhea lasting 14 days or more",
      low_weight: "Visible severe wasting / very low weight for age",
      pallor: "Palmar pallor (pale palms — possible anemia)",
      mild_fever_only: "Mild fever, no other danger signs",
      mild_cough_no_fast_breathing: "Cough/cold, no fast breathing",
      mild_diarrhea_no_dehydration: "Loose stools, no signs of dehydration",
    },
    keywords: {
      fever_no_stiff_neck: ["fever", "temperature", "hot", "warm body"],
      chest_indrawing: ["chest", "indrawing", "breathing difficulty", "chest sinking"],
      fast_breathing: ["fast breathing", "rapid breathing", "breathes fast", "quick breath"],
      vomits_everything: ["vomiting everything", "vomits everything", "vomit all", "throws up everything"],
      mild_diarrhea_no_dehydration: ["loose stool", "diarrhea", "watery stool", "loose motion"],
      convulsions: ["fits", "seizure", "convulsion", "shaking", "jerking"],
      lethargic_unconscious: ["unconscious", "lethargic", "not waking", "drowsy", "won't wake"],
      not_able_to_drink: ["not drinking", "can't drink", "refuses breastfeed", "not breastfeeding"],
      blood_in_stool: ["blood in stool", "bloody stool", "blood in poop", "red stool"],
      high_fever_with_stiff_neck: ["stiff neck", "neck stiff", "can't bend neck", "neck rigid"],
      some_dehydration: ["sunken eyes", "dehydration", "not urinating", "dry mouth"],
      stridor: ["stridor", "noisy breathing", "wheezing", "breathing noise"],
      ear_pain_discharge: ["ear pain", "ear discharge", "ear infection", "ear pus"],
      pallor: ["pale", "pallor", "anemia", "pale palms", "white palms"],
      low_weight: ["low weight", "underweight", "wasting", "thin child", "not gaining weight"],
    },
  },

  // ── Hindi ────────────────────────────────────────────────────────────────────
  hi: {
    meta: { name: "Hindi", nativeName: "हिंदी", locale: "hi-IN", whisperLang: "hi" },
    ui: {
      appName: "ASHA साथी",
      tagline: "WHO IMNCI · ऑफलाइन ट्रायज सिस्टम",
      offlineReady: "ऑफलाइन तैयार",
      newAssessment: "नई जाँच",
      newAssessmentSub: "नए मरीज़ की जाँच शुरू करें",
      viewQueue: "आज की कतार",
      viewQueueSub: "मरीज़ों की सूची देखें",
      referralHistory: "रेफरल इतिहास",
      referralHistorySub: "पिछले रेफरल यहाँ सुरक्षित हैं",
      patientName: "मरीज़ का नाम (वैकल्पिक)",
      patientNamePlaceholder: "नाम लिखें या खाली छोड़ें",
      ageGroup: "उम्र का समूह",
      gender: "लिंग",
      male: "पुरुष",
      female: "महिला",
      startVoice: "🎤 आवाज़ से जाँच शुरू करें",
      skipChecklist: "आवाज़ छोड़ें · सूची इस्तेमाल करें",
      checklistTitle: "खतरे के संकेत सूची",
      checklistSubtitle: "WHO IMNCI प्रोटोकॉल",
      noSignsSelected: "कोई संकेत नहीं चुना",
      signsSelected: (n) => `${n} संकेत चुने गए`,
      clearAll: "सब हटाएं",
      assessPatient: "मरीज़ की जाँच करें →",
      selectAtLeastOne: "कम से कम एक संकेत चुनें",
      voiceIdle: "शुरू हो रहा है...",
      voiceLoading: "आवाज़ मॉडल लोड हो रहा है (पहली बार)...",
      voiceReady: "🎤 बोलने के लिए दबाएं",
      voiceRecording: "🔴 रिकॉर्डिंग... रोकने के लिए दबाएं",
      voiceTranscribing: "आवाज़ पहचान रहे हैं...",
      voiceError: "आवाज़ उपलब्ध नहीं — सूची इस्तेमाल करें",
      voiceHeard: "सुना",
      noiseNote: "पृष्ठभूमि शोर कम हो रहा है",
      referImmediately: "तुरंत अस्पताल भेजें",
      referIn24h: "24 घंटे में अस्पताल भेजें",
      localManagement: "घर पर देखभाल",
      speakResult: "🔊 परिणाम सुनें",
      addToQueue: "कतार में जोड़ें →",
      backToChecklist: "सूची पर वापस जाएं",
      observedSigns: "देखे गए खतरे के संकेत",
      familyHeadingRed: "तुरंत अस्पताल जाएं",
      familySubRed: "बच्चे को अभी PHC ले जाना ज़रूरी है",
      familyUrgencyRed: "देरी खतरनाक हो सकती है",
      familyHeadingYellow: "24 घंटे में डॉक्टर को दिखाएं",
      familySubYellow: "बच्चे को कल तक PHC ले जाएं",
      familyUrgencyYellow: "जल्द इलाज ज़रूरी है",
      familyHeadingGreen: "घर पर देखभाल करें",
      familySubGreen: "अभी अस्पताल जाने की ज़रूरत नहीं है",
      familyUrgencyGreen: "नियमित देखभाल जारी रखें",
      familySignsLabel: "देखे गए खतरे के संकेत",
      familyListen: "🔊 सुनें",
      familyProtocol: "यह जानकारी WHO IMNCI प्रोटोकॉल पर आधारित है",
      familyPatient: "मरीज़",
      queueTitle: "आज की कतार",
      queueSubtitle: (n) => `${n} मरीज़ · गंभीरता के अनुसार`,
      addNextPatient: "+ अगला मरीज़ जोड़ें",
      viewReport: "रिपोर्ट देखें",
      markReferred: "रेफर किया",
      referred: "✓ रेफर हो गया",
      ageGroups: ["शिशु (<1 साल)", "बच्चा (1-5 साल)", "बड़ा बच्चा (5-12)", "वयस्क"],
    },
    signs: {
      not_able_to_drink: "पी नहीं सकता / दूध नहीं पी रहा",
      vomits_everything: "सब उल्टी कर देता है",
      convulsions: "झटके / दौरे — अभी या हाल ही में",
      lethargic_unconscious: "बेहोश या नींद से नहीं उठता",
      chest_indrawing: "सांस लेते समय छाती अंदर धंसती है",
      stridor: "शांत बच्चे की सांस में आवाज़",
      severe_dehydration: "आँखें धंसी हुई + त्वचा खिंचने पर धीरे आती है",
      blood_in_stool: "मल में खून",
      high_fever_with_stiff_neck: "तेज़ बुखार + गर्दन अकड़ी",
      bulging_fontanelle: "सिर का नरम हिस्सा उभरा या धंसा (शिशु)",
      fast_breathing: "तेज़ सांस",
      some_dehydration: "बेचैन/चिड़चिड़ा + आँखें थोड़ी धंसी",
      fever_no_stiff_neck: "बुखार, गर्दन ठीक है",
      ear_pain_discharge: "कान में दर्द या पानी",
      persistent_diarrhea: "14 दिन से अधिक दस्त",
      low_weight: "बहुत दुबला / उम्र के अनुसार बहुत कम वज़न",
      pallor: "हथेली पीली — खून की कमी",
      mild_fever_only: "हल्का बुखार, अन्य कोई संकेत नहीं",
      mild_cough_no_fast_breathing: "खांसी/सर्दी, सांस तेज़ नहीं",
      mild_diarrhea_no_dehydration: "ढीले दस्त, पानी की कमी नहीं",
    },
    keywords: {
      fever_no_stiff_neck: ["bukhar", "bukhaar", "tap", "tapp", "बुखार", "गर्मी"],
      chest_indrawing: ["seena", "saans", "saas", "chest", "chhaati", "सांस", "छाती"],
      fast_breathing: ["tez saas", "tezi se saans", "jaldi saans", "तेज़ सांस"],
      vomits_everything: ["ulti", "sab ulti", "ulti ho rahi", "उल्टी", "सब उल्टी"],
      mild_diarrhea_no_dehydration: ["dast", "loose", "potty", "दस्त", "ढीला"],
      convulsions: ["jhatke", "jhatkay", "fits", "daure", "झटके", "दौरे"],
      lethargic_unconscious: ["behosh", "uthta nahi", "neend", "nahi uth", "बेहोश", "नींद"],
      not_able_to_drink: ["pi nahi", "dudh nahi", "pee nahi", "पी नहीं", "दूध नहीं"],
      blood_in_stool: ["khoon", "stool mein khoon", "खून", "मल में खून"],
      high_fever_with_stiff_neck: ["gardan", "gardan akad", "stiff neck", "गर्दन", "अकड़"],
      some_dehydration: ["aankhein andar", "aankhein", "dehaidrashion", "आँखें", "पानी की कमी"],
      stridor: ["awaaz", "noise breath", "saans ki awaaz", "आवाज़", "सांस में आवाज़"],
      ear_pain_discharge: ["kaan", "kan dard", "kaan se paani", "कान", "कान दर्द"],
      pallor: ["safed haath", "pale", "pallor", "खून की कमी", "पीला"],
      low_weight: ["wajan nahi", "kam wajan", "dubla", "वज़न", "दुबला"],
    },
  },

  // ── Marathi ──────────────────────────────────────────────────────────────────
  mr: {
    meta: { name: "Marathi", nativeName: "मराठी", locale: "mr-IN", whisperLang: "mr" },
    ui: {
      appName: "ASHA साथी",
      tagline: "WHO IMNCI · ऑफलाइन ट्रायज प्रणाली",
      offlineReady: "ऑफलाइन तयार",
      newAssessment: "नवीन तपासणी",
      newAssessmentSub: "नवीन रुग्णाची तपासणी सुरू करा",
      viewQueue: "आजची रांग",
      viewQueueSub: "रुग्णांची यादी पाहा",
      referralHistory: "रेफरल इतिहास",
      referralHistorySub: "मागील रेफरल येथे साठवले आहेत",
      patientName: "रुग्णाचे नाव (पर्यायी)",
      patientNamePlaceholder: "नाव लिहा किंवा रिकामे सोडा",
      ageGroup: "वयोगट",
      gender: "लिंग",
      male: "पुरुष",
      female: "स्त्री",
      startVoice: "🎤 आवाजाने तपासणी सुरू करा",
      skipChecklist: "आवाज सोडा · यादी वापरा",
      checklistTitle: "धोक्याच्या खुणांची यादी",
      checklistSubtitle: "WHO IMNCI प्रोटोकॉल",
      noSignsSelected: "कोणतीही खूण निवडली नाही",
      signsSelected: (n) => `${n} खुणा निवडल्या`,
      clearAll: "सर्व काढा",
      assessPatient: "रुग्णाची तपासणी करा →",
      selectAtLeastOne: "किमान एक खूण निवडा",
      voiceIdle: "सुरू होत आहे...",
      voiceLoading: "आवाज मॉडेल लोड होत आहे (पहिल्यांदा)...",
      voiceReady: "🎤 बोलण्यासाठी दाबा",
      voiceRecording: "🔴 रेकॉर्डिंग... थांबवण्यासाठी दाबा",
      voiceTranscribing: "आवाज ओळखत आहे...",
      voiceError: "आवाज उपलब्ध नाही — यादी वापरा",
      voiceHeard: "ऐकले",
      noiseNote: "पार्श्वभूमी आवाज कमी होत आहे",
      referImmediately: "ताबडतोब रुग्णालयात पाठवा",
      referIn24h: "24 तासांत रुग्णालयात पाठवा",
      localManagement: "घरी काळजी",
      speakResult: "🔊 निकाल ऐका",
      addToQueue: "रांगेत जोडा →",
      backToChecklist: "यादीवर परत जा",
      observedSigns: "आढळलेल्या धोक्याच्या खुणा",
      familyHeadingRed: "ताबडतोब रुग्णालयात जा",
      familySubRed: "मुलाला आत्ताच PHC ला न्या",
      familyUrgencyRed: "उशीर धोकादायक असू शकतो",
      familyHeadingYellow: "24 तासांत डॉक्टरांना दाखवा",
      familySubYellow: "उद्यापर्यंत PHC ला न्या",
      familyUrgencyYellow: "लवकर उपचार आवश्यक आहे",
      familyHeadingGreen: "घरी काळजी घ्या",
      familySubGreen: "आत्ता रुग्णालयात जाण्याची गरज नाही",
      familyUrgencyGreen: "नियमित काळजी सुरू ठेवा",
      familySignsLabel: "आढळलेल्या धोक्याच्या खुणा",
      familyListen: "🔊 ऐका",
      familyProtocol: "ही माहिती WHO IMNCI प्रोटोकॉलवर आधारित आहे",
      familyPatient: "रुग्ण",
      queueTitle: "आजची रांग",
      queueSubtitle: (n) => `${n} रुग्ण · तातडीनुसार`,
      addNextPatient: "+ पुढील रुग्ण जोडा",
      viewReport: "अहवाल पाहा",
      markReferred: "रेफर केले",
      referred: "✓ रेफर झाले",
      ageGroups: ["शिशू (<1 वर्ष)", "मूल (1-5 वर्षे)", "मोठे मूल (5-12)", "प्रौढ"],
    },
    signs: {
      not_able_to_drink: "पिऊ शकत नाही / दूध पीत नाही",
      vomits_everything: "सर्व उलट्या करतो",
      convulsions: "झटके / फेफरे — आत्ता किंवा नुकतेच",
      lethargic_unconscious: "बेशुद्ध किंवा जागे होत नाही",
      chest_indrawing: "श्वास घेताना छाती आत जाते",
      stridor: "शांत मुलाच्या श्वासात आवाज",
      severe_dehydration: "डोळे खोल गेलेले + त्वचा ओढल्यावर हळू येते",
      blood_in_stool: "शौचात रक्त",
      high_fever_with_stiff_neck: "तीव्र ताप + मान ताठ",
      bulging_fontanelle: "डोक्यावरील मऊ भाग उंचावलेला किंवा खोल (शिशू)",
      fast_breathing: "जलद श्वास",
      some_dehydration: "अस्वस्थ/चिडचिड + डोळे थोडे खोल",
      fever_no_stiff_neck: "ताप, मान ठीक",
      ear_pain_discharge: "कानात दुखणे किंवा पाणी",
      persistent_diarrhea: "14 दिवसांपेक्षा जास्त जुलाब",
      low_weight: "खूप कृश / वयाप्रमाणे कमी वजन",
      pallor: "तळहात पांढरे — रक्ताची कमतरता",
      mild_fever_only: "सौम्य ताप, इतर कोणतीही खूण नाही",
      mild_cough_no_fast_breathing: "खोकला/सर्दी, श्वास जलद नाही",
      mild_diarrhea_no_dehydration: "सैल जुलाब, पाण्याची कमतरता नाही",
    },
    keywords: {
      fever_no_stiff_neck: ["taap", "tap", "ताप", "तापमान", "उष्णता"],
      chest_indrawing: ["shvaas", "chhaati", "श्वास", "छाती", "दम"],
      fast_breathing: ["jald shvaas", "tez shvaas", "जलद श्वास", "वेगाने श्वास"],
      vomits_everything: ["ulti", "okaari", "उलटी", "ओकारी", "सर्व उलटी"],
      mild_diarrhea_no_dehydration: ["julaab", "shet", "जुलाब", "शेट", "पातळ"],
      convulsions: ["jhatke", "fefre", "झटके", "फेफरे", "आकडी"],
      lethargic_unconscious: ["beshudha", "uthena", "जागे नाही", "बेशुद्ध", "झोपेतून उठेना"],
      not_able_to_drink: ["pit nahi", "doodh nahi", "पीत नाही", "दूध नाही"],
      blood_in_stool: ["raktaa", "shouchat rakt", "रक्त", "शौचात रक्त"],
      high_fever_with_stiff_neck: ["maan taath", "man akad", "मान ताठ", "मान अकडली"],
      some_dehydration: ["dole aaat", "pani kami", "डोळे खोल", "पाण्याची कमतरता"],
      stridor: ["shvaasaat aavaz", "श्वासात आवाज", "घरघर"],
      ear_pain_discharge: ["kaan", "kaanaat dukh", "कान", "कानात दुखणे"],
      pallor: ["pand", "pandhar", "पांढरे", "रक्ताची कमतरता"],
      low_weight: ["wajan kami", "krusha", "वजन कमी", "कृश"],
    },
  },

  // ── Tamil ────────────────────────────────────────────────────────────────────
  ta: {
    meta: { name: "Tamil", nativeName: "தமிழ்", locale: "ta-IN", whisperLang: "ta" },
    ui: {
      appName: "ASHA சாத்தி",
      tagline: "WHO IMNCI · ஆஃப்லைன் ட்ரையேஜ் கணினி",
      offlineReady: "ஆஃப்லைன் தயார்",
      newAssessment: "புதிய மதிப்பீடு",
      newAssessmentSub: "புதிய நோயாளிக்கு ட்ரையேஜ் தொடங்கு",
      viewQueue: "இன்றைய வரிசை",
      viewQueueSub: "நோயாளிகளின் பட்டியலைக் காண்க",
      referralHistory: "பரிந்துரை வரலாறு",
      referralHistorySub: "முந்தைய பரிந்துரைகள் இங்கே சேமிக்கப்பட்டன",
      patientName: "நோயாளியின் பெயர் (விரும்பினால்)",
      patientNamePlaceholder: "பெயரை உள்ளிடவும் அல்லது காலியாக விடவும்",
      ageGroup: "வயதுக் குழு",
      gender: "பாலினம்",
      male: "ஆண்",
      female: "பெண்",
      startVoice: "🎤 குரல் மூலம் மதிப்பீடு தொடங்கு",
      skipChecklist: "குரலை தவிர்க்கவும் · பட்டியலைப் பயன்படுத்தவும்",
      checklistTitle: "ஆபத்தான அறிகுறிகள் பட்டியல்",
      checklistSubtitle: "WHO IMNCI நெறிமுறை",
      noSignsSelected: "எந்த அறிகுறியும் தேர்ந்தெடுக்கப்படவில்லை",
      signsSelected: (n) => `${n} அறிகுறிகள் தேர்ந்தெடுக்கப்பட்டன`,
      clearAll: "அனைத்தையும் அழிக்கவும்",
      assessPatient: "நோயாளியை மதிப்பிடவும் →",
      selectAtLeastOne: "குறைந்தது ஒரு அறிகுறியை தேர்ந்தெடுக்கவும்",
      voiceIdle: "தொடங்குகிறது...",
      voiceLoading: "குரல் மாதிரி ஏற்றுகிறது (முதல் முறை)...",
      voiceReady: "🎤 பேசுவதற்கு அழுத்தவும்",
      voiceRecording: "🔴 பதிவு நடக்கிறது... நிறுத்த அழுத்தவும்",
      voiceTranscribing: "குரலை செயலாக்குகிறது...",
      voiceError: "குரல் கிடைக்கவில்லை — பட்டியலைப் பயன்படுத்தவும்",
      voiceHeard: "கேட்டது",
      noiseNote: "பின்னணி சத்தம் குறைக்கப்படுகிறது",
      referImmediately: "உடனடியாக மருத்துவமனைக்கு அனுப்பவும்",
      referIn24h: "24 மணி நேரத்தில் அனுப்பவும்",
      localManagement: "வீட்டில் பராமரிப்பு",
      speakResult: "🔊 முடிவைக் கேளுங்கள்",
      addToQueue: "வரிசையில் சேர்க்கவும் →",
      backToChecklist: "பட்டியலுக்குத் திரும்பவும்",
      observedSigns: "கண்டறியப்பட்ட ஆபத்தான அறிகுறிகள்",
      familyHeadingRed: "உடனடியாக மருத்துவமனைக்கு செல்லுங்கள்",
      familySubRed: "குழந்தையை இப்போதே PHC-க்கு அழைத்துச் செல்லுங்கள்",
      familyUrgencyRed: "தாமதம் ஆபத்தானது",
      familyHeadingYellow: "24 மணி நேரத்தில் மருத்துவரை சந்தியுங்கள்",
      familySubYellow: "நாளை PHC-க்கு அழைத்துச் செல்லுங்கள்",
      familyUrgencyYellow: "விரைவான சிகிச்சை அவசியம்",
      familyHeadingGreen: "வீட்டில் பராமரிப்பு",
      familySubGreen: "இப்போது மருத்துவமனைக்கு செல்ல வேண்டாம்",
      familyUrgencyGreen: "வழக்கமான பராமரிப்பைத் தொடரவும்",
      familySignsLabel: "கண்டறியப்பட்ட அறிகுறிகள்",
      familyListen: "🔊 கேளுங்கள்",
      familyProtocol: "இந்த தகவல் WHO IMNCI நெறிமுறையை அடிப்படையாகக் கொண்டது",
      familyPatient: "நோயாளி",
      queueTitle: "இன்றைய வரிசை",
      queueSubtitle: (n) => `${n} நோயாளிகள் · அவசரத்தின் படி`,
      addNextPatient: "+ அடுத்த நோயாளியை சேர்க்கவும்",
      viewReport: "அறிக்கையைக் காண்க",
      markReferred: "பரிந்துரைக்கப்பட்டது",
      referred: "✓ பரிந்துரைக்கப்பட்டது",
      ageGroups: ["குழந்தை (<1 வருடம்)", "சிறுவன் (1-5 வருடம்)", "பெரிய குழந்தை (5-12)", "வயதுவந்தோர்"],
    },
    signs: {
      not_able_to_drink: "குடிக்க / தாய்ப்பால் குடிக்க முடியவில்லை",
      vomits_everything: "எல்லாவற்றையும் வாந்தி எடுக்கிறது",
      convulsions: "வலிப்பு — இப்போது அல்லது சமீபத்தில்",
      lethargic_unconscious: "மயக்கம் அல்லது விழிப்படையவில்லை",
      chest_indrawing: "மூச்சு விடும்போது மார்பு உள்ளே போகிறது",
      stridor: "அமைதியான குழந்தையின் மூச்சில் சத்தம்",
      severe_dehydration: "கண்கள் உள்ளே போனது + தோல் மெதுவாக திரும்புகிறது",
      blood_in_stool: "மலத்தில் இரத்தம்",
      high_fever_with_stiff_neck: "அதிக காய்ச்சல் + கழுத்து இறுகல்",
      bulging_fontanelle: "மண்டையோட்டின் மென்மையான பகுதி வீக்கம் / குழிந்திருக்கிறது",
      fast_breathing: "வேகமான மூச்சு",
      some_dehydration: "அமைதியற்ற + கண்கள் சிறிது உள்ளே",
      fever_no_stiff_neck: "காய்ச்சல், கழுத்து சரியாக உள்ளது",
      ear_pain_discharge: "காது வலி அல்லது சீழ்",
      persistent_diarrhea: "14 நாட்களுக்கும் மேல் வயிற்றுப்போக்கு",
      low_weight: "மிகவும் மெலிந்திருப்பு / வயதுக்கு மிகவும் குறைந்த எடை",
      pallor: "உள்ளங்கை வெளிர்ப்பு — இரத்த சோகை",
      mild_fever_only: "சிறிய காய்ச்சல், வேறு எந்த அறிகுறியும் இல்லை",
      mild_cough_no_fast_breathing: "இருமல்/சளி, மூச்சு வேகமில்லை",
      mild_diarrhea_no_dehydration: "தளர்வான மலம், நீர்ச்சத்து குறைவில்லை",
    },
    keywords: {
      fever_no_stiff_neck: ["kaycchal", "jaram", "காய்ச்சல்", "ஜுரம்"],
      chest_indrawing: ["moocchu", "maarbu", "மூச்சு", "மார்பு"],
      fast_breathing: ["vega moocchu", "வேக மூச்சு"],
      vomits_everything: ["vaanthi", "எல்லாம் வாந்தி", "வாந்தி"],
      mild_diarrhea_no_dehydration: ["vayiru", "வயிற்றுப்போக்கு", "தளர்வான"],
      convulsions: ["valippu", "வலிப்பு"],
      lethargic_unconscious: ["mayakkam", "விழிப்பில்லை", "மயக்கம்"],
      not_able_to_drink: ["kudikka maateno", "தாய்ப்பால் இல்லை", "குடிக்க மாட்டேன்"],
      blood_in_stool: ["malattil iratham", "மலத்தில் இரத்தம்"],
      high_fever_with_stiff_neck: ["kazhutu", "கழுத்து இறுகல்"],
      some_dehydration: ["kannkal", "கண்கள் உள்ளே", "தண்ணீர் குறைவு"],
      stridor: ["moocchil sattam", "மூச்சில் சத்தம்"],
      ear_pain_discharge: ["kaadhu", "காது", "காது வலி"],
      pallor: ["venmai", "வெளிர்ப்பு", "இரத்த சோகை"],
      low_weight: ["edam", "எடை குறைவு", "மெலிந்திருப்பு"],
    },
  },

  // ── Telugu ───────────────────────────────────────────────────────────────────
  te: {
    meta: { name: "Telugu", nativeName: "తెలుగు", locale: "te-IN", whisperLang: "te" },
    ui: {
      appName: "ASHA సాధి",
      tagline: "WHO IMNCI · ఆఫ్‌లైన్ ట్రయేజ్ సిస్టమ్",
      offlineReady: "ఆఫ్‌లైన్ సిద్ధంగా ఉంది",
      newAssessment: "కొత్త అంచనా",
      newAssessmentSub: "కొత్త రోగికి ట్రయేజ్ ప్రారంభించండి",
      viewQueue: "నేటి క్యూ",
      viewQueueSub: "రోగుల జాబితా చూడండి",
      referralHistory: "రెఫరల్ చరిత్ర",
      referralHistorySub: "మునుపటి రెఫరల్‌లు ఇక్కడ నిల్వ చేయబడ్డాయి",
      patientName: "రోగి పేరు (ఐచ్ఛికం)",
      patientNamePlaceholder: "పేరు నమోదు చేయండి లేదా ఖాళీగా వదిలేయండి",
      ageGroup: "వయస్సు సమూహం",
      gender: "లింగం",
      male: "పురుషుడు",
      female: "మహిళ",
      startVoice: "🎤 వాయిస్ అసెస్‌మెంట్ ప్రారంభించండి",
      skipChecklist: "వాయిస్ దాటవేయండి · జాబితా ఉపయోగించండి",
      checklistTitle: "ప్రమాద సంకేతాల జాబితా",
      checklistSubtitle: "WHO IMNCI ప్రోటోకాల్",
      noSignsSelected: "ఏ సంకేతం ఎంచుకోబడలేదు",
      signsSelected: (n) => `${n} సంకేతాలు ఎంచుకోబడ్డాయి`,
      clearAll: "అన్నింటినీ తొలగించండి",
      assessPatient: "రోగిని అంచనా వేయండి →",
      selectAtLeastOne: "కనీసం ఒక సంకేతాన్ని ఎంచుకోండి",
      voiceIdle: "ప్రారంభమవుతోంది...",
      voiceLoading: "వాయిస్ మోడల్ లోడ్ అవుతోంది (మొదటిసారి)...",
      voiceReady: "🎤 మాట్లాడటానికి నొక్కండి",
      voiceRecording: "🔴 రికార్డింగ్... ఆపడానికి నొక్కండి",
      voiceTranscribing: "వాయిస్ ప్రాసెస్ అవుతోంది...",
      voiceError: "వాయిస్ అందుబాటులో లేదు — జాబితా ఉపయోగించండి",
      voiceHeard: "విన్నది",
      noiseNote: "నేపథ్య శబ్దం తగ్గించబడుతోంది",
      referImmediately: "వెంటనే ఆసుపత్రికి పంపండి",
      referIn24h: "24 గంటల్లో పంపండి",
      localManagement: "ఇంట్లో సంరక్షణ",
      speakResult: "🔊 ఫలితాన్ని వినండి",
      addToQueue: "క్యూలో చేర్చండి →",
      backToChecklist: "జాబితాకు తిరిగి వెళ్ళండి",
      observedSigns: "గమనించిన ప్రమాద సంకేతాలు",
      familyHeadingRed: "వెంటనే ఆసుపత్రికి వెళ్ళండి",
      familySubRed: "పిల్లవాడిని ఇప్పుడే PHC కి తీసుకువెళ్ళండి",
      familyUrgencyRed: "ఆలస్యం ప్రమాదకరం",
      familyHeadingYellow: "24 గంటల్లో డాక్టర్‌ని చూడండి",
      familySubYellow: "రేపటికల్లా PHC కి తీసుకువెళ్ళండి",
      familyUrgencyYellow: "త్వరిత చికిత్స అవసరం",
      familyHeadingGreen: "ఇంట్లో సంరక్షణ చేయండి",
      familySubGreen: "ఇప్పుడు ఆసుపత్రికి వెళ్ళాల్సిన అవసరం లేదు",
      familyUrgencyGreen: "సాధారణ సంరక్షణ కొనసాగించండి",
      familySignsLabel: "గమనించిన సంకేతాలు",
      familyListen: "🔊 వినండి",
      familyProtocol: "ఈ సమాచారం WHO IMNCI ప్రోటోకాల్ ఆధారంగా ఉంది",
      familyPatient: "రోగి",
      queueTitle: "నేటి క్యూ",
      queueSubtitle: (n) => `${n} రోగులు · అత్యవసరత ప్రకారం`,
      addNextPatient: "+ తదుపరి రోగిని చేర్చండి",
      viewReport: "నివేదిక చూడండి",
      markReferred: "రెఫర్ చేయబడింది",
      referred: "✓ రెఫర్ చేయబడింది",
      ageGroups: ["శిశువు (<1 సంవత్సరం)", "చిన్నారి (1-5 సం.)", "పెద్ద పిల్లవాడు (5-12)", "వయోజనుడు"],
    },
    signs: {
      not_able_to_drink: "తాగలేకపోవడం / పాలు తాగలేకపోవడం",
      vomits_everything: "అన్నీ వాంతి చేసుకుంటున్నాడు",
      convulsions: "మూర్ఛలు — ఇప్పుడు లేదా ఇటీవల",
      lethargic_unconscious: "మూర్ఛ లేదా మేల్కొనడం కష్టం",
      chest_indrawing: "శ్వాస తీసుకున్నప్పుడు ఛాతీ లోపలికి వెళ్తోంది",
      stridor: "ప్రశాంతంగా ఉన్న పిల్లవాడి శ్వాసలో శబ్దం",
      severe_dehydration: "కళ్ళు లోపలికి వెళ్ళాయి + చర్మం నెమ్మదిగా తిరిగి వస్తోంది",
      blood_in_stool: "మలంలో రక్తం",
      high_fever_with_stiff_neck: "అధిక జ్వరం + మెడ బిగుసుకోవడం",
      bulging_fontanelle: "తలపై మెత్తని స్థలం ఉబ్బడం / లోపలికి వెళ్ళడం",
      fast_breathing: "వేగంగా శ్వాస",
      some_dehydration: "అశాంతి + కళ్ళు కొంచెం లోపలికి",
      fever_no_stiff_neck: "జ్వరం, మెడ సాధారణంగా ఉంది",
      ear_pain_discharge: "చెవి నొప్పి లేదా చీము",
      persistent_diarrhea: "14 రోజులకు మించి విరేచనాలు",
      low_weight: "చాలా బక్కగా / వయసుకు చాలా తక్కువ బరువు",
      pallor: "అరచేయి తెల్లగా — రక్తహీనత",
      mild_fever_only: "తేలికపాటి జ్వరం, వేరే సంకేతాలు లేవు",
      mild_cough_no_fast_breathing: "దగ్గు/జలుబు, వేగంగా శ్వాస లేదు",
      mild_diarrhea_no_dehydration: "సన్నగా విరేచనాలు, నీటి కొరత లేదు",
    },
    keywords: {
      fever_no_stiff_neck: ["jwaram", "veppam", "జ్వరం", "వేడి"],
      chest_indrawing: ["svaasa", "chaati", "శ్వాస", "ఛాతీ"],
      fast_breathing: ["veganga svaasa", "వేగంగా శ్వాస"],
      vomits_everything: ["vaanti", "anni vaanti", "వాంతి"],
      mild_diarrhea_no_dehydration: ["virechanalu", "విరేచనాలు"],
      convulsions: ["moorcha", "మూర్ఛ"],
      lethargic_unconscious: ["nidra", "మేల్కొనడం కష్టం", "మూర్ఛ"],
      not_able_to_drink: ["tagadam ledu", "paalu tagadam ledu", "తాగలేకపోవడం"],
      blood_in_stool: ["malam lo raktam", "మలంలో రక్తం"],
      high_fever_with_stiff_neck: ["meda bigusukavaDam", "మెడ బిగుసుకోవడం"],
      some_dehydration: ["kallu lopali", "కళ్ళు లోపలికి", "నీటి కొరత"],
      stridor: ["svaasalo sabdam", "శ్వాసలో శబ్దం"],
      ear_pain_discharge: ["cheevi", "చెవి", "చెవి నొప్పి"],
      pallor: ["tella", "రక్తహీనత", "తెల్లగా"],
      low_weight: ["baruvu takkuva", "బరువు తక్కువ"],
    },
  },

  // ── Kannada ──────────────────────────────────────────────────────────────────
  kn: {
    meta: { name: "Kannada", nativeName: "ಕನ್ನಡ", locale: "kn-IN", whisperLang: "kn" },
    ui: {
      appName: "ASHA ಸಾಥಿ",
      tagline: "WHO IMNCI · ಆಫ್‌ಲೈನ್ ಟ್ರಯೇಜ್ ವ್ಯವಸ್ಥೆ",
      offlineReady: "ಆಫ್‌ಲೈನ್ ಸಿದ್ಧ",
      newAssessment: "ಹೊಸ ಮೌಲ್ಯಮಾಪನ",
      newAssessmentSub: "ಹೊಸ ರೋಗಿಗೆ ಟ್ರಯೇಜ್ ಪ್ರಾರಂಭಿಸಿ",
      viewQueue: "ಇಂದಿನ ಸಾಲು",
      viewQueueSub: "ರೋಗಿಗಳ ಪಟ್ಟಿ ನೋಡಿ",
      referralHistory: "ರೆಫರಲ್ ಇತಿಹಾಸ",
      referralHistorySub: "ಹಿಂದಿನ ರೆಫರಲ್‌ಗಳು ಇಲ್ಲಿ ಸಂಗ್ರಹಿಸಲಾಗಿದೆ",
      patientName: "ರೋಗಿಯ ಹೆಸರು (ಐಚ್ಛಿಕ)",
      patientNamePlaceholder: "ಹೆಸರು ನಮೂದಿಸಿ ಅಥವಾ ಖಾಲಿ ಬಿಡಿ",
      ageGroup: "ವಯಸ್ಸಿನ ಗುಂಪು",
      gender: "ಲಿಂಗ",
      male: "ಪುರುಷ",
      female: "ಮಹಿಳೆ",
      startVoice: "🎤 ಧ್ವನಿ ಮೂಲಕ ಮೌಲ್ಯಮಾಪನ ಪ್ರಾರಂಭಿಸಿ",
      skipChecklist: "ಧ್ವನಿ ಬಿಡಿ · ಪಟ್ಟಿ ಬಳಸಿ",
      checklistTitle: "ಅಪಾಯದ ಚಿಹ್ನೆಗಳ ಪಟ್ಟಿ",
      checklistSubtitle: "WHO IMNCI ಪ್ರೋಟೋಕಾಲ್",
      noSignsSelected: "ಯಾವುದೇ ಚಿಹ್ನೆ ಆರಿಸಲಾಗಿಲ್ಲ",
      signsSelected: (n) => `${n} ಚಿಹ್ನೆಗಳು ಆರಿಸಲಾಗಿದೆ`,
      clearAll: "ಎಲ್ಲವನ್ನೂ ತೆಗೆ",
      assessPatient: "ರೋಗಿಯನ್ನು ಮೌಲ್ಯಮಾಪನ ಮಾಡಿ →",
      selectAtLeastOne: "ಕನಿಷ್ಠ ಒಂದು ಚಿಹ್ನೆ ಆರಿಸಿ",
      voiceIdle: "ಪ್ರಾರಂಭವಾಗುತ್ತಿದೆ...",
      voiceLoading: "ಧ್ವನಿ ಮಾದರಿ ಲೋಡ್ ಆಗುತ್ತಿದೆ (ಮೊದಲ ಬಾರಿ)...",
      voiceReady: "🎤 ಮಾತನಾಡಲು ಒತ್ತಿ",
      voiceRecording: "🔴 ರೆಕಾರ್ಡ್ ಆಗುತ್ತಿದೆ... ನಿಲ್ಲಿಸಲು ಒತ್ತಿ",
      voiceTranscribing: "ಧ್ವನಿ ಸಂಸ್ಕರಿಸಲಾಗುತ್ತಿದೆ...",
      voiceError: "ಧ್ವನಿ ಲಭ್ಯವಿಲ್ಲ — ಪಟ್ಟಿ ಬಳಸಿ",
      voiceHeard: "ಕೇಳಿದ್ದು",
      noiseNote: "ಹಿನ್ನೆಲೆ ಶಬ್ದ ಕಡಿಮೆ ಆಗುತ್ತಿದೆ",
      referImmediately: "ತಕ್ಷಣ ಆಸ್ಪತ್ರೆಗೆ ಕಳಿಸಿ",
      referIn24h: "24 ಗಂಟೆಯಲ್ಲಿ ಕಳಿಸಿ",
      localManagement: "ಮನೆಯಲ್ಲಿ ಆರೈಕೆ",
      speakResult: "🔊 ಫಲಿತಾಂಶ ಕೇಳಿ",
      addToQueue: "ಸಾಲಿಗೆ ಸೇರಿಸಿ →",
      backToChecklist: "ಪಟ್ಟಿಗೆ ಹಿಂತಿರುಗಿ",
      observedSigns: "ಗಮನಿಸಿದ ಅಪಾಯದ ಚಿಹ್ನೆಗಳು",
      familyHeadingRed: "ತಕ್ಷಣ ಆಸ್ಪತ್ರೆಗೆ ಹೋಗಿ",
      familySubRed: "ಮಗುವನ್ನು ಈಗಲೇ PHC ಗೆ ಕರೆದೊಯ್ಯಿ",
      familyUrgencyRed: "ತಡ ಅಪಾಯಕಾರಿ",
      familyHeadingYellow: "24 ಗಂಟೆಯಲ್ಲಿ ವೈದ್ಯರನ್ನು ಕಾಣಿ",
      familySubYellow: "ನಾಳೆಯೊಳಗೆ PHC ಗೆ ಕರೆದೊಯ್ಯಿ",
      familyUrgencyYellow: "ತ್ವರಿತ ಚಿಕಿತ್ಸೆ ಅಗತ್ಯ",
      familyHeadingGreen: "ಮನೆಯಲ್ಲಿ ಆರೈಕೆ ಮಾಡಿ",
      familySubGreen: "ಈಗ ಆಸ್ಪತ್ರೆಗೆ ಹೋಗಬೇಕಿಲ್ಲ",
      familyUrgencyGreen: "ನಿಯಮಿತ ಆರೈಕೆ ಮುಂದುವರೆಸಿ",
      familySignsLabel: "ಗಮನಿಸಿದ ಚಿಹ್ನೆಗಳು",
      familyListen: "🔊 ಕೇಳಿ",
      familyProtocol: "ಈ ಮಾಹಿತಿ WHO IMNCI ಪ್ರೋಟೋಕಾಲ್ ಆಧಾರಿತ",
      familyPatient: "ರೋಗಿ",
      queueTitle: "ಇಂದಿನ ಸಾಲು",
      queueSubtitle: (n) => `${n} ರೋಗಿಗಳು · ತುರ್ತು ಪ್ರಕಾರ`,
      addNextPatient: "+ ಮುಂದಿನ ರೋಗಿ ಸೇರಿಸಿ",
      viewReport: "ವರದಿ ನೋಡಿ",
      markReferred: "ರೆಫರ್ ಮಾಡಲಾಗಿದೆ",
      referred: "✓ ರೆಫರ್ ಆಗಿದೆ",
      ageGroups: ["ಶಿಶು (<1 ವರ್ಷ)", "ಮಗು (1-5 ವರ್ಷ)", "ದೊಡ್ಡ ಮಗು (5-12)", "ವಯಸ್ಕ"],
    },
    signs: {
      not_able_to_drink: "ಕುಡಿಯಲು / ಹಾಲು ಕುಡಿಯಲು ಆಗುತ್ತಿಲ್ಲ",
      vomits_everything: "ಎಲ್ಲವನ್ನೂ ವಾಂತಿ ಮಾಡುತ್ತಿದೆ",
      convulsions: "ಅಪಸ್ಮಾರ / ಸೆಳೆತ — ಈಗ ಅಥವಾ ಇತ್ತೀಚೆಗೆ",
      lethargic_unconscious: "ಪ್ರಜ್ಞಾಹೀನ ಅಥವಾ ಎಚ್ಚರ ಆಗಲು ಕಷ್ಟ",
      chest_indrawing: "ಉಸಿರಾಟದ ಸಮಯ ಎದೆ ಒಳಗೆ ಹೋಗುತ್ತಿದೆ",
      stridor: "ಶಾಂತ ಮಗುವಿನ ಉಸಿರಾಟದಲ್ಲಿ ಸದ್ದು",
      severe_dehydration: "ಕಣ್ಣುಗಳು ಒಳಗೆ ಹೋಗಿವೆ + ಚರ್ಮ ನಿಧಾನ ಮರಳಿ ಬರುತ್ತದೆ",
      blood_in_stool: "ಮಲದಲ್ಲಿ ರಕ್ತ",
      high_fever_with_stiff_neck: "ತೀವ್ರ ಜ್ವರ + ಕತ್ತು ಗಟ್ಟಿ",
      bulging_fontanelle: "ತಲೆಯ ಮೃದು ಭಾಗ ಉಬ್ಬಿದೆ / ಒಳಗೆ ಹೋಗಿದೆ",
      fast_breathing: "ವೇಗವಾದ ಉಸಿರಾಟ",
      some_dehydration: "ಅಶಾಂತ + ಕಣ್ಣುಗಳು ಸ್ವಲ್ಪ ಒಳಗೆ",
      fever_no_stiff_neck: "ಜ್ವರ, ಕತ್ತು ಸಾಮಾನ್ಯ",
      ear_pain_discharge: "ಕಿವಿ ನೋವು ಅಥವಾ ಸ್ರಾವ",
      persistent_diarrhea: "14 ದಿನಕ್ಕಿಂತ ಹೆಚ್ಚು ಭೇದಿ",
      low_weight: "ತೀವ್ರ ಕೃಶತ / ವಯಸ್ಸಿಗೆ ಕಡಿಮೆ ತೂಕ",
      pallor: "ಅಂಗೈ ಬಿಳುಪು — ರಕ್ತಹೀನತೆ",
      mild_fever_only: "ಸೌಮ್ಯ ಜ್ವರ, ಬೇರೆ ಚಿಹ್ನೆ ಇಲ್ಲ",
      mild_cough_no_fast_breathing: "ಕೆಮ್ಮು/ಶೀತ, ವೇಗದ ಉಸಿರಾಟ ಇಲ್ಲ",
      mild_diarrhea_no_dehydration: "ಸಡಿಲ ಭೇದಿ, ನಿರ್ಜಲೀಕರಣ ಇಲ್ಲ",
    },
    keywords: {
      fever_no_stiff_neck: ["jwara", "tapamana", "ಜ್ವರ", "ಉಷ್ಣ"],
      chest_indrawing: ["usiraata", "edhe", "ಉಸಿರಾಟ", "ಎದೆ"],
      fast_breathing: ["vega usiraata", "ವೇಗ ಉಸಿರಾಟ"],
      vomits_everything: ["vaanti", "ಎಲ್ಲ ವಾಂತಿ", "ವಾಂತಿ"],
      mild_diarrhea_no_dehydration: ["bhedi", "ಭೇದಿ"],
      convulsions: ["seleta", "ಅಪಸ್ಮಾರ", "ಸೆಳೆತ"],
      lethargic_unconscious: ["prajna", "ಪ್ರಜ್ಞಾಹೀನ", "ಎಚ್ಚರ ಇಲ್ಲ"],
      not_able_to_drink: ["kudiyalu agilla", "ಕುಡಿಯಲು ಆಗಲ್ಲ"],
      blood_in_stool: ["malada rakta", "ಮಲದಲ್ಲಿ ರಕ್ತ"],
      high_fever_with_stiff_neck: ["kattu gatti", "ಕತ್ತು ಗಟ್ಟಿ"],
      some_dehydration: ["kannugalu", "ಕಣ್ಣು ಒಳಗೆ", "ನೀರಿನ ಕೊರತೆ"],
      stridor: ["usiraatadalli saddu", "ಉಸಿರಾಟದಲ್ಲಿ ಸದ್ದು"],
      ear_pain_discharge: ["kivi", "ಕಿವಿ", "ಕಿವಿ ನೋವು"],
      pallor: ["biluppu", "ಬಿಳುಪು", "ರಕ್ತಹೀನತೆ"],
      low_weight: ["tuuka kadi", "ತೂಕ ಕಡಿಮೆ"],
    },
  },

  // ── Bengali ──────────────────────────────────────────────────────────────────
  bn: {
    meta: { name: "Bengali", nativeName: "বাংলা", locale: "bn-IN", whisperLang: "bn" },
    ui: {
      appName: "ASHA সাথী",
      tagline: "WHO IMNCI · অফলাইন ট্রায়াজ সিস্টেম",
      offlineReady: "অফলাইন প্রস্তুত",
      newAssessment: "নতুন মূল্যায়ন",
      newAssessmentSub: "নতুন রোগীর ট্রায়াজ শুরু করুন",
      viewQueue: "আজকের সারি",
      viewQueueSub: "রোগীদের তালিকা দেখুন",
      referralHistory: "রেফারেল ইতিহাস",
      referralHistorySub: "আগের রেফারেলগুলি এখানে সংরক্ষিত",
      patientName: "রোগীর নাম (ঐচ্ছিক)",
      patientNamePlaceholder: "নাম লিখুন বা খালি রাখুন",
      ageGroup: "বয়সের গ্রুপ",
      gender: "লিঙ্গ",
      male: "পুরুষ",
      female: "মহিলা",
      startVoice: "🎤 ভয়েস মূল্যায়ন শুরু করুন",
      skipChecklist: "ভয়েস এড়িয়ে যান · তালিকা ব্যবহার করুন",
      checklistTitle: "বিপদ চিহ্নের তালিকা",
      checklistSubtitle: "WHO IMNCI প্রোটোকল",
      noSignsSelected: "কোনো চিহ্ন নির্বাচিত নয়",
      signsSelected: (n) => `${n}টি চিহ্ন নির্বাচিত`,
      clearAll: "সব মুছুন",
      assessPatient: "রোগী মূল্যায়ন করুন →",
      selectAtLeastOne: "কমপক্ষে একটি চিহ্ন নির্বাচন করুন",
      voiceIdle: "শুরু হচ্ছে...",
      voiceLoading: "ভয়েস মডেল লোড হচ্ছে (প্রথমবার)...",
      voiceReady: "🎤 কথা বলতে চাপুন",
      voiceRecording: "🔴 রেকর্ড হচ্ছে... থামাতে চাপুন",
      voiceTranscribing: "ভয়েস প্রক্রিয়া হচ্ছে...",
      voiceError: "ভয়েস পাওয়া যাচ্ছে না — তালিকা ব্যবহার করুন",
      voiceHeard: "শোনা গেছে",
      noiseNote: "পটভূমির শব্দ কমানো হচ্ছে",
      referImmediately: "এখনই হাসপাতালে পাঠান",
      referIn24h: "২৪ ঘণ্টার মধ্যে পাঠান",
      localManagement: "বাড়িতে যত্ন",
      speakResult: "🔊 ফলাফল শুনুন",
      addToQueue: "সারিতে যোগ করুন →",
      backToChecklist: "তালিকায় ফিরুন",
      observedSigns: "দেখা বিপদ চিহ্ন",
      familyHeadingRed: "এখনই হাসপাতালে যান",
      familySubRed: "শিশুকে এখনই PHC-তে নিয়ে যান",
      familyUrgencyRed: "দেরি বিপজ্জনক হতে পারে",
      familyHeadingYellow: "২৪ ঘণ্টার মধ্যে ডাক্তার দেখান",
      familySubYellow: "আগামীকালের মধ্যে PHC-তে নিয়ে যান",
      familyUrgencyYellow: "দ্রুত চিকিৎসা প্রয়োজন",
      familyHeadingGreen: "বাড়িতে যত্ন করুন",
      familySubGreen: "এখন হাসপাতালে যাওয়ার দরকার নেই",
      familyUrgencyGreen: "নিয়মিত যত্ন চালিয়ে যান",
      familySignsLabel: "দেখা চিহ্নগুলি",
      familyListen: "🔊 শুনুন",
      familyProtocol: "এই তথ্য WHO IMNCI প্রোটোকলের উপর ভিত্তি করে",
      familyPatient: "রোগী",
      queueTitle: "আজকের সারি",
      queueSubtitle: (n) => `${n}জন রোগী · জরুরিতা অনুযায়ী`,
      addNextPatient: "+ পরবর্তী রোগী যোগ করুন",
      viewReport: "রিপোর্ট দেখুন",
      markReferred: "রেফার করা হয়েছে",
      referred: "✓ রেফার হয়েছে",
      ageGroups: ["শিশু (<১ বছর)", "বাচ্চা (১-৫ বছর)", "বড় বাচ্চা (৫-১২)", "বয়স্ক"],
    },
    signs: {
      not_able_to_drink: "পান করতে / বুকের দুধ খেতে পারছে না",
      vomits_everything: "সব বমি করে দিচ্ছে",
      convulsions: "খিঁচুনি — এখন বা সম্প্রতি",
      lethargic_unconscious: "অচেতন বা জাগানো কঠিন",
      chest_indrawing: "শ্বাস নেওয়ার সময় বুক ভেতরে যাচ্ছে",
      stridor: "শান্ত শিশুর শ্বাসে শব্দ",
      severe_dehydration: "চোখ ভেতরে গেছে + চামড়া ধীরে ফিরে আসে",
      blood_in_stool: "পায়খানায় রক্ত",
      high_fever_with_stiff_neck: "তীব্র জ্বর + ঘাড় শক্ত",
      bulging_fontanelle: "মাথার নরম জায়গা ফুলে গেছে / ভেতরে গেছে",
      fast_breathing: "দ্রুত শ্বাস",
      some_dehydration: "অস্থির + চোখ একটু ভেতরে",
      fever_no_stiff_neck: "জ্বর, ঘাড় ঠিক আছে",
      ear_pain_discharge: "কানে ব্যথা বা পুঁজ",
      persistent_diarrhea: "১৪ দিনের বেশি ডায়রিয়া",
      low_weight: "খুব রোগা / বয়সের তুলনায় কম ওজন",
      pallor: "হাতের তালু ফ্যাকাশে — রক্তশূন্যতা",
      mild_fever_only: "হালকা জ্বর, অন্য কোনো চিহ্ন নেই",
      mild_cough_no_fast_breathing: "কাশি/ঠান্ডা, দ্রুত শ্বাস নেই",
      mild_diarrhea_no_dehydration: "আলগা পায়খানা, পানিশূন্যতা নেই",
    },
    keywords: {
      fever_no_stiff_neck: ["jwar", "jwor", "জ্বর", "তাপমাত্রা"],
      chest_indrawing: ["shwas", "buk", "শ্বাস", "বুক"],
      fast_breathing: ["duto shwas", "দ্রুত শ্বাস"],
      vomits_everything: ["bomi", "sab bomi", "বমি", "সব বমি"],
      mild_diarrhea_no_dehydration: ["diarriya", "ডায়রিয়া", "আলগা"],
      convulsions: ["khichhuni", "খিঁচুনি"],
      lethargic_unconscious: ["achetana", "অচেতন", "জাগানো কঠিন"],
      not_able_to_drink: ["pan korate parche na", "পান করতে পারছে না"],
      blood_in_stool: ["paykhanay rakt", "পায়খানায় রক্ত"],
      high_fever_with_stiff_neck: ["ghar shakto", "ঘাড় শক্ত"],
      some_dehydration: ["chokh bhitore", "চোখ ভেতরে", "পানিশূন্যতা"],
      stridor: ["shwase shabdo", "শ্বাসে শব্দ"],
      ear_pain_discharge: ["kan", "কান", "কানে ব্যথা"],
      pallor: ["phekaashe", "ফ্যাকাশে", "রক্তশূন্যতা"],
      low_weight: ["kam wajon", "কম ওজন", "রোগা"],
    },
  },

  // ── Gujarati ─────────────────────────────────────────────────────────────────
  gu: {
    meta: { name: "Gujarati", nativeName: "ગુજરાતી", locale: "gu-IN", whisperLang: "gu" },
    ui: {
      appName: "ASHA સાથી",
      tagline: "WHO IMNCI · ઓફલાઇન ટ્રાયેજ સિસ્ટમ",
      offlineReady: "ઓફલાઇન તૈયાર",
      newAssessment: "નવું મૂલ્યાંકન",
      newAssessmentSub: "નવા દર્દી માટે ટ્રાયેજ શરૂ કરો",
      viewQueue: "આજની કતાર",
      viewQueueSub: "દર્દીઓની યાદી જુઓ",
      referralHistory: "રેફરલ ઇતિહાસ",
      referralHistorySub: "અગાઉના રેફરલ અહીં સ્ટોર કર્યા",
      patientName: "દર્દીનું નામ (વૈકલ્પિક)",
      patientNamePlaceholder: "નામ દાખલ કરો અથવા ખાલી રાખો",
      ageGroup: "ઉંમર જૂથ",
      gender: "લિંગ",
      male: "પુરુષ",
      female: "સ્ત્રી",
      startVoice: "🎤 અવાજ દ્વારા મૂલ્યાંકન શરૂ કરો",
      skipChecklist: "અવાજ છોડો · યાદી વાપરો",
      checklistTitle: "જોખમના ચિહ્નોની યાદી",
      checklistSubtitle: "WHO IMNCI પ્રોટોકોલ",
      noSignsSelected: "કોઈ ચિહ્ન પસંદ નથી",
      signsSelected: (n) => `${n} ચિહ્નો પસંદ`,
      clearAll: "બધું સ્પષ્ટ કરો",
      assessPatient: "દર્દીનું મૂલ્યાંકન કરો →",
      selectAtLeastOne: "ઓછામાં ઓછું એક ચિહ્ન પસંદ કરો",
      voiceIdle: "શરૂ થઈ રહ્યું છે...",
      voiceLoading: "અવાજ મોડલ લોડ થઈ રહ્યું છે (પ્રથમ વખત)...",
      voiceReady: "🎤 બોલવા માટે દબાવો",
      voiceRecording: "🔴 રેકોર્ડ થઈ રહ્યું છે... રોકવા માટે દબાવો",
      voiceTranscribing: "અવાજ પ્રોસેસ થઈ રહ્યો છે...",
      voiceError: "અવાજ ઉપલબ્ધ નથી — યાદી વાપરો",
      voiceHeard: "સાંભળ્યું",
      noiseNote: "પૃષ્ઠભૂ અવાજ ઘટી રહ્યો છે",
      referImmediately: "તરત જ હોસ્પિટલ મોકલો",
      referIn24h: "24 કલાકમાં મોકલો",
      localManagement: "ઘરે સારવાર",
      speakResult: "🔊 પરિણામ સાંભળો",
      addToQueue: "કતારમાં ઉમેરો →",
      backToChecklist: "યાદી પર પાછા જાઓ",
      observedSigns: "જોવાયેલ જોખમ ચિહ્નો",
      familyHeadingRed: "તરત જ હોસ્પિટલ જાઓ",
      familySubRed: "બાળકને અત્યારે PHC લઈ જાઓ",
      familyUrgencyRed: "વિલંબ જોખમી હોઈ શકે",
      familyHeadingYellow: "24 કલાકમાં ડૉક્ટર પાસે જાઓ",
      familySubYellow: "કાલ સુધી PHC લઈ જાઓ",
      familyUrgencyYellow: "ઝડપી સારવાર જરૂરી",
      familyHeadingGreen: "ઘરે સારવાર કરો",
      familySubGreen: "અત્યારે હોસ્પિટલ જવાની જરૂર નથી",
      familyUrgencyGreen: "નિયમિત સંભાળ ચાલુ રાખો",
      familySignsLabel: "જોવાયેલ ચિહ્નો",
      familyListen: "🔊 સાંભળો",
      familyProtocol: "આ માહિતી WHO IMNCI પ્રોટોકોલ પર આધારિત",
      familyPatient: "દર્દી",
      queueTitle: "આજની કતાર",
      queueSubtitle: (n) => `${n} દર્દીઓ · તાકીદ પ્રમાણે`,
      addNextPatient: "+ આગળ દર્દી ઉમેરો",
      viewReport: "રિપોર્ટ જુઓ",
      markReferred: "રેફર કર્યો",
      referred: "✓ રેફર થઈ ગયો",
      ageGroups: ["શિશુ (<1 વર્ષ)", "બાળક (1-5 વર્ષ)", "મોટું બાળક (5-12)", "પ્રૌઢ"],
    },
    signs: {
      not_able_to_drink: "પી શકતો/તી નથી / સ્તનપાન કરી શકતો/તી નથી",
      vomits_everything: "બધું ઊલટી કરે છે",
      convulsions: "આંચકી — હમણાં અથવા તાજેતરમાં",
      lethargic_unconscious: "બેભાન અથવા જગાડવા કઠિન",
      chest_indrawing: "શ્વાસ લેતી વખતે છાતી અંદર ધસે",
      stridor: "શાંત બાળકના શ્વાસમાં અવાજ",
      severe_dehydration: "આંખો અંદર ગઈ + ચામડી ધીમે પાછી આવે",
      blood_in_stool: "ઝાડામાં લોહી",
      high_fever_with_stiff_neck: "તેઝ તાવ + ગળું જકડાઈ ગઈ",
      bulging_fontanelle: "માથાની નરમ જગ્યા ઉભરી / ધંસી",
      fast_breathing: "ઝડપી શ્વાસ",
      some_dehydration: "અશાંત + આંખો થોડી અંદર",
      fever_no_stiff_neck: "તાવ, ગળું ઠીક",
      ear_pain_discharge: "કાનમાં દુ:ખાવો અથવા સ્રાવ",
      persistent_diarrhea: "14 દિવસ કરતા વધુ ઝાડા",
      low_weight: "ખૂબ ક્ષીણ / ઉંમર મુજબ ઓછું વજન",
      pallor: "હથેળી ફ્લેફ — એનિમિયા",
      mild_fever_only: "હળવો તાવ, અન્ય ચિહ્ન નહીં",
      mild_cough_no_fast_breathing: "ઉધરસ/શરદી, ઝડપ શ્વાસ નહીં",
      mild_diarrhea_no_dehydration: "ઢીળા ઝાડા, નિર્જળીકરણ નહીં",
    },
    keywords: {
      fever_no_stiff_neck: ["tav", "taav", "તાવ", "ગરમી"],
      chest_indrawing: ["shvaas", "chhati", "શ્વાસ", "છાતી"],
      fast_breathing: ["ઝડપ શ્વાસ"],
      vomits_everything: ["ulti", "badhu ulti", "ઊલટી"],
      mild_diarrhea_no_dehydration: ["zada", "ઝાડા"],
      convulsions: ["aanchki", "આંચકી"],
      lethargic_unconscious: ["behosh", "બેભાન"],
      not_able_to_drink: ["pi shakta nathi", "પી શકતો નથી"],
      blood_in_stool: ["zadama lohi", "ઝાડામાં લોહી"],
      high_fever_with_stiff_neck: ["galtu jakadai", "ગળું જકડાઈ"],
      some_dehydration: ["aankho andar", "આંખો અંદર"],
      stridor: ["shvaasma avaj", "શ્વાસમાં અવાજ"],
      ear_pain_discharge: ["kan", "કાન", "કાનમાં દુ:ખ"],
      pallor: ["pheke", "ફ્લેફ", "એનિમિયા"],
      low_weight: ["vazan ochu", "વજન ઓછું"],
    },
  },
};

/** Returns the language config for the given key, defaulting to English. */
export function getLang(langKey) {
  return LANGUAGES[langKey] || LANGUAGES.en;
}

/** Ordered list for the language picker */
export const LANGUAGE_LIST = [
  { key: "hi", label: "हिंदी", sublabel: "Hindi" },
  { key: "mr", label: "मराठी", sublabel: "Marathi" },
  { key: "ta", label: "தமிழ்", sublabel: "Tamil" },
  { key: "te", label: "తెలుగు", sublabel: "Telugu" },
  { key: "kn", label: "ಕನ್ನಡ", sublabel: "Kannada" },
  { key: "bn", label: "বাংলা", sublabel: "Bengali" },
  { key: "gu", label: "ગુજરાતી", sublabel: "Gujarati" },
  { key: "en", label: "English", sublabel: "English" },
];